# Generated by Django 5.2.5 on 2025-08-21 10:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_info', models.CharField(blank=True, max_length=255, null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_processes', models.IntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitoring.host')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cmdline', models.TextField(blank=True, null=True)),
                ('parent_pid', models.IntegerField(blank=True, null=True)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('memory_percent', models.FloatField(default=0.0)),
                ('memory_rss', models.BigIntegerField(default=0)),
                ('memory_vms', models.BigIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.FloatField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='monitoring.processsnapshot')),
            ],
            options={
                'ordering': ['pid'],
                'indexes': [models.Index(fields=['snapshot', 'parent_pid'], name='monitoring__snapsho_e4b65e_idx'), models.Index(fields=['snapshot', 'pid'], name='monitoring__snapsho_e629fb_idx')],
            },
        ),
    ]
