services:
  - type: web
    name: process-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: process-monitor-db
    plan: free
